// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtrlmydcxygfbpivwpjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0cmxteWRjeHlnZmJwaXZ3cGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NjkxODksImV4cCI6MjA3MTE0NTE4OX0.fr4x_oEgRroSsiDhxD8wHiWKkjd3gYkWe7FB6rjojYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});